# Generated by Django 4.2.6 on 2023-10-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=100)),
                ('portada', models.ImageField(upload_to='aplicacion_a/images/')),
                ('audio', models.FileField(upload_to='aplicacion_a/audios/')),
            ],
        ),
    ]
