# Generated by Django 4.2.6 on 2023-10-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_a', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('portada', models.ImageField(upload_to='aplicacion_a/portada')),
                ('parrafo', models.TextField(max_length=600)),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
